# Generated by Django 3.2 on 2021-06-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='area', max_length=100, unique=True, verbose_name='地名')),
            ],
        ),
        migrations.CreateModel(
            name='Media_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True, verbose_name='評価数')),
            ],
        ),
        migrations.CreateModel(
            name='Media_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=10, unique=True, verbose_name='媒体名')),
                ('official_name', models.CharField(default='name', max_length=20, verbose_name='正式名称')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='name', max_length=100, verbose_name='店名')),
                ('yomigana', models.CharField(blank=True, max_length=100, null=True, verbose_name='ヨミガナ')),
                ('store_name_gn', models.CharField(blank=True, max_length=100, null=True, verbose_name='店名gn')),
                ('store_name_hp', models.CharField(blank=True, max_length=100, null=True, verbose_name='店名hp')),
                ('store_name_tb', models.CharField(blank=True, max_length=100, null=True, verbose_name='店名tb')),
                ('store_name_retty', models.CharField(blank=True, max_length=100, null=True, verbose_name='店名retty')),
                ('store_name_demaekan', models.CharField(blank=True, max_length=100, null=True, verbose_name='店名demaekan')),
                ('store_name_uber', models.CharField(blank=True, max_length=100, null=True, verbose_name='店名uber')),
                ('store_name_google', models.CharField(blank=True, max_length=100, null=True, verbose_name='店名google')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('category1', models.CharField(blank=True, max_length=100, null=True)),
                ('category2', models.CharField(blank=True, max_length=100, null=True)),
                ('category3', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrape.area', verbose_name='エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('log_num_byTabelog', models.IntegerField(blank=True, null=True, verbose_name='ログ数_食べログ')),
                ('review_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.media_data')),
            ],
        ),
        migrations.AddField(
            model_name='media_data',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.media_type'),
        ),
        migrations.AddField(
            model_name='media_data',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.store'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('store_name', 'area'), name='unique_storearea'),
        ),
        migrations.AddConstraint(
            model_name='media_data',
            constraint=models.UniqueConstraint(fields=('store', 'media_type'), name='unique_storemedia'),
        ),
    ]
