# Generated by Django 3.2 on 2021-04-08 05:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='area', max_length=100, unique=True, verbose_name='地名')),
            ],
        ),
        migrations.CreateModel(
            name='Media_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True, verbose_name='評価数')),
            ],
        ),
        migrations.CreateModel(
            name='Media_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=10, unique=True, verbose_name='媒体名')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='name', max_length=50, unique=True, verbose_name='店名')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrape.area', verbose_name='エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('log_num_byTabelog', models.IntegerField(blank=True, null=True, verbose_name='ログ数_食べログ')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.media_data')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.store')),
            ],
        ),
        migrations.AddField(
            model_name='media_data',
            name='media_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.media_type'),
        ),
        migrations.AddField(
            model_name='media_data',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.store'),
        ),
    ]
