# Generated by Django 3.2 on 2021-04-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_demaekan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_gn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_google',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_hp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_retty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_tb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_uber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名'),
        ),
        migrations.AddConstraint(
            model_name='media_data',
            constraint=models.UniqueConstraint(fields=('store_id', 'media_type_id'), name='unique_storemedia'),
        ),
    ]
