# Generated by Django 3.2 on 2021-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='yomi_roma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='yomi'),
        ),
        migrations.AddField(
            model_name='area',
            name='yomigana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='よみ'),
        ),
        migrations.AddField(
            model_name='store',
            name='yomi_roma',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='yomigana'),
        ),
    ]
