# Generated by Django 3.2 on 2021-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20210613_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='yomigana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='よみがな'),
        ),
    ]
