# Generated by Django 3.2 on 2021-06-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_store_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='category',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='store',
            name='category2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='category3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
