# Generated by Django 3.2 on 2021-04-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20210409_0701'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='media_data',
            name='unique_storemedia',
        ),
        migrations.RenameField(
            model_name='media_data',
            old_name='media_type_id',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='media_data',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_demaekan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名demaekan'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_gn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名gn'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_google',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名google'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_hp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名hp'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_retty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名retty'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_tb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名tb'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_uber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店名uber'),
        ),
        migrations.AddConstraint(
            model_name='media_data',
            constraint=models.UniqueConstraint(fields=('store', 'media_type'), name='unique_storemedia'),
        ),
    ]
