# Generated by Django 3.2 on 2021-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20210409_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
