# Generated by Django 3.2 on 2021-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_alter_store_yomigana'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_data',
            name='collected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
