# Generated by Django 3.2 on 2021-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_alter_store_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('store_name', 'area'), name='unique_storearea'),
        ),
    ]
