# Generated by Django 3.2 on 2021-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_store_unique_storearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='name', max_length=50, verbose_name='店名'),
        ),
    ]
