# Generated by Django 3.2 on 2021-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_alter_store_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_type',
            name='official_name',
            field=models.CharField(default='name', max_length=20, verbose_name='正式名称'),
        ),
    ]
