# Generated by Django 3.2 on 2021-05-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0008_media_type_official_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name_uber',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='店名uber'),
        ),
    ]
