# Generated by Django 3.2 on 2021-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0009_alter_store_store_name_uber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='name', max_length=80, verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_demaekan',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='店名demaekan'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_gn',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='店名gn'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_google',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='店名google'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_hp',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='店名hp'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_retty',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='店名retty'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_tb',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='店名tb'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_uber',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='店名uber'),
        ),
    ]
