# Generated by Django 3.2 on 2021-05-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0011_auto_20210522_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_data',
            name='url',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
